apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmspaymentinstrument
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdmspaymentinstrument
  template:
    metadata:
      labels:
        app: bpdmspaymentinstrument
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: bpdmspaymentinstrument
          image: cstaruatregistry.azurecr.io/bpdmspaymentinstrument
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: bpdmspaymentinstrument
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: eventhub-common-tkm
            - configMapRef:
                name: bpdmspaymentinstrument
            - configMapRef:
                name: jvm
          resources:
            limits:
              cpu: 800m
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          imagePullPolicy: Always
      hostAliases:
        - hostnames:
            - bpd-event-uat.servicebus.windows.net
          ip: 10.70.67.5
